'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';

type Trade = { id:string; type:'BUY'|'SELL'; tokenAddress:string; symbol?:string; amountUsd?:number; proceedsUsd?:number; priceUsd:number; pnlUsd?:number; reason?:string; at:string; mode?:string };
type Position = { id:string; tokenAddress:string; symbol?:string; amountUsd:number; entryPriceUsd:number; currentPriceUsd:number; quantity:number; openedAt:string; score?:number; grade?:string; source?:string };
type ScannerStats = { startedAt?:string; discoveryRuns?:number; refreshRuns?:number; apiErrors?:number; candidatesDiscovered?:number; poolsReceived?:number; tokensScored?:number; filtered?:number; watched?:number; signals?:number; };
type Candidate = { tokenAddress?:string; address?:string; symbol?:string; score?:number; grade?:string; riskPassed?:boolean; liquidityUsd?:number; priceUsd?:number; priceChange5mPct?:number; volume5mUsd?:number };

const nav = [['Dashboard','⌂'],['Daily P/L','▣'],['Positions','◈'],['Trades','⇄'],['Signals','◇'],['Bot Controls','⚙'],['Risk Settings','◉'],['Calculator','⌁'],['Profit Goals','◎'],['Settings','⚙']] as const;
const API = { engine:'http://localhost:8790', scanner:'http://localhost:8787' };
const money=(n:number)=>`${n<0?'-':'+'}$${Math.abs(n).toFixed(2)}`;
const fmtUsd=(n:number)=>`$${Number(n||0).toFixed(2)}`;
const fmtPct=(n:number)=>`${n>=0?'+':''}${Number(n||0).toFixed(2)}%`;

function Stat({icon,title,value,sub,tone}:{icon:string;title:string;value:string;sub:string;tone:string}){return <div className="kpi"><div className={`kpi-icon ${tone}`}>{icon}</div><div className="kpi-copy"><span>{title}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Panel({title,sub,badge,children,className='' }:{title:string;sub?:string;badge?:string;children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{badge&&<em>{badge}</em>}</div>{children}</section>}
function StatusDot({ok,amber=false}:{ok:boolean;amber?:boolean}){return <span className={`dot ${amber?'amber':''} ${ok?'':'offline'}`}/>}
function Field({label,value,set,suffix}:{label:string;value:string;set?:(v:string)=>void;suffix?:string}){return <label className="field"><span>{label}{suffix&&<i>{suffix}</i>}</span><input value={value} onChange={e=>set?.(e.target.value)} readOnly={!set}/></label>}

export default function Home(){
 const [tab,setTab]=useState<(typeof nav)[number][0]>('Dashboard');
 const [positions,setPositions]=useState<Position[]>([]); const [trades,setTrades]=useState<Trade[]>([]); const [scanner,setScanner]=useState<ScannerStats>({}); const [candidates,setCandidates]=useState<Candidate[]>([]);
 const [engineOk,setEngineOk]=useState(false); const [scannerOk,setScannerOk]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [paused,setPaused]=useState(false); const [size,setSize]=useState('10'); const [sl,setSl]=useState('12'); const [tp,setTp]=useState('25'); const [goal,setGoal]=useState('1000');
 const refresh=useCallback(async()=>{setError(''); try { const [h,p,t,s,c]=await Promise.allSettled([fetch(`${API.engine}/health`),fetch(`${API.engine}/positions`),fetch(`${API.engine}/trades`),fetch(`${API.scanner}/stats`),fetch(`${API.scanner}/candidates`)]); if(h.status==='fulfilled'&&h.value.ok){setEngineOk(true)}else setEngineOk(false); if(p.status==='fulfilled'&&p.value.ok)setPositions(await p.value.json()); if(t.status==='fulfilled'&&t.value.ok)setTrades(await t.value.json()); if(s.status==='fulfilled'&&s.value.ok){setScanner(await s.value.json());setScannerOk(true)}else setScannerOk(false); if(c.status==='fulfilled'&&c.value.ok)setCandidates(await c.value.json()); } catch(e){setError('Local services are unavailable. Start the scanner and trading engine.');setEngineOk(false);setScannerOk(false)} finally{setLoading(false)}},[]);
 useEffect(()=>{refresh();const id=setInterval(refresh,3000);return()=>clearInterval(id)},[refresh]);
 const stats=useMemo(()=>{const sells=trades.filter(t=>t.type==='SELL');const pnl=sells.reduce((a,t)=>a+Number(t.pnlUsd||0),0);const wins=sells.filter(t=>Number(t.pnlUsd||0)>0).length;const losses=sells.filter(t=>Number(t.pnlUsd||0)<0).length;const today=new Date().toDateString();const todayPnl=sells.filter(t=>new Date(t.at).toDateString()===today).reduce((a,t)=>a+Number(t.pnlUsd||0),0);return {pnl,todayPnl,wins,losses,winRate:sells.length?wins/sells.length*100:0,trades:sells.length}} , [trades]);
 const equity=100+stats.pnl+positions.reduce((a,p)=>a+(Number(p.currentPriceUsd)-Number(p.entryPriceUsd))*Number(p.quantity),0);
 const daily=useMemo(()=>{const m=new Map<string,number>();trades.filter(t=>t.type==='SELL').forEach(t=>{const d=new Date(t.at);const k=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;m.set(k,(m.get(k)||0)+Number(t.pnlUsd||0))});return m},[trades]);
 const monthly=useMemo(()=>Array.from({length:12},(_,i)=>trades.filter(t=>t.type==='SELL'&&new Date(t.at).getMonth()===i&&new Date(t.at).getFullYear()===new Date().getFullYear()).reduce((a,t)=>a+Number(t.pnlUsd||0),0)),[trades]);
 const close=async(p:Position)=>{try{const r=await fetch(`${API.engine}/positions/${encodeURIComponent(p.tokenAddress)}/close`,{method:'POST',headers:{authorization:'Bearer meme-trader-local-2026'}});if(!r.ok)throw new Error();await refresh()}catch{setError('Close failed. Check that the engine is running and the position still exists.')}};
 const year=new Date().getFullYear(), month=new Date().getMonth();
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">✦</div><div><b>MEME<br/><strong>TRADER BOT</strong></b><small>TRADING TERMINAL</small></div></div><div className="paper-card"><StatusDot ok={engineOk}/><span>PAPER MODE</span><small>SAFE EXECUTION</small></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([name,icon])=><button key={name} onClick={()=>setTab(name)} className={tab===name?'nav-item active':'nav-item'}><span className="nav-icon">{icon}</span>{name}</button>)}</nav><div className="sidebar-bottom"><div className="nav-label">SYSTEM</div><div className="connection"><StatusDot ok={engineOk}/><div><b>Trading Engine</b><small>{API.engine}</small></div><strong>{engineOk?'OK':'OFF'}</strong></div><div className="connection"><StatusDot ok={scannerOk} amber={!scannerOk}/><div><b>Live Scanner</b><small>{scannerOk?`${scanner.signals||0} signals`:'Offline'}</small></div><strong>{scannerOk?'OK':'OFF'}</strong></div><div className="safe-box"><span>◈</span><div><b>Paper funds only</b><small>Wallet credentials are not used</small></div></div></div></aside>
 <main className="content"><header className="topbar"><div><div className="breadcrumb">SOLANA <span>/</span> MEME STRATEGY</div><h1>{tab}</h1><p>Real-time trading control center</p></div><div className="top-actions"><div className="system-pill"><StatusDot ok={!paused}/>{paused?'BOT PAUSED':'BOT RUNNING'}</div><button className="icon-btn" onClick={refresh}>↻</button><div className="user">MT</div></div></header>{error&&<div className="error-banner">⚠ {error}<button onClick={()=>setError('')}>×</button></div>}
 {tab==='Dashboard'&&<><div className="kpis"><Stat icon="▣" title="ACCOUNT EQUITY" value={fmtUsd(equity)} sub="Paper account • $100 start" tone="green"/><Stat icon="↗" title="TODAY'S P&L" value={money(stats.todayPnl)} sub={stats.trades?`${fmtPct(stats.todayPnl/equity*100)} today`:'No closed trades'} tone="cyan"/><Stat icon="◈" title="TOTAL P&L" value={money(stats.pnl)} sub={`${stats.trades} closed trades`} tone="purple"/><Stat icon="◎" title="WIN RATE" value={`${stats.winRate.toFixed(1)}%`} sub={`${stats.wins}W / ${stats.losses}L`} tone="pink"/><Stat icon="▰" title="OPEN POSITIONS" value={`${positions.length}`} sub="Active positions" tone="orange"/></div><div className="dashboard-grid"><Panel title="Equity Curve" sub="Live paper-account performance" badge="LIVE"><EquityChart trades={trades} positions={positions}/></Panel><Panel title="Bot Controls" sub="Execution & risk" badge={paused?'PAUSED':'RUNNING'}><div className="control-buttons"><button className="pause-btn" onClick={()=>setPaused(!paused)}>{paused?'▶ Resume Bot':'Ⅱ Pause Bot'}</button><button className="stop-btn" onClick={()=>positions.forEach(close)}>● Close All</button></div><div className="control-list"><div><span>Max Position Size</span><b>${size}.00</b></div><div><span>Stop Loss</span><b>{sl}%</b></div><div><span>Take Profit</span><b>{tp}%</b></div><div><span>Max Concurrent</span><b>5</b></div></div><button className="advanced" onClick={()=>setTab('Risk Settings')}>Advanced Settings <span>›</span></button></Panel></div><div className="dashboard-grid lower-grid"><Panel title="Open Positions" sub="Live positions from trading engine" badge={`${positions.length} OPEN`} className="positions-panel"><PositionTable positions={positions} onClose={close}/></Panel><Panel title="Recent Activity" sub="Scanner and execution events" badge="LIVE"><ActivityList trades={trades} candidates={candidates}/></Panel></div></>}
 {tab==='Daily P/L'&&<div className="page-stack"><div className="kpis compact"><Stat icon="↗" title="YEAR TO DATE" value={money(monthly.reduce((a,b)=>a+b,0))} sub={`${year} realized P/L`} tone="green"/><Stat icon="▣" title="CURRENT MONTH" value={money(monthly[month])} sub={new Date().toLocaleString('en-US',{month:'long'})} tone="cyan"/><Stat icon="★" title="BEST MONTH" value={money(Math.max(...monthly))} sub="Best realized month" tone="purple"/><Stat icon="▤" title="TRADING DAYS" value={`${Array.from(daily.values()).filter(Boolean).length}`} sub="Days with realized P/L" tone="orange"/></div><div className="pnl-layout"><Panel title={`${new Date().toLocaleString('en-US',{month:'long'})} Daily P/L`} sub="Every calendar day from actual engine trades"><Calendar daily={daily} year={year} month={month}/></Panel><Panel title={`${year} Monthly P/L`} sub="Actual realized P/L by month"><div className="monthly-list">{monthly.map((v,i)=><div className="monthly" key={i}><span>{new Date(year,i,1).toLocaleString('en-US',{month:'short'})}</span><div><i style={{width:`${Math.min(100,Math.abs(v)/Math.max(1,...monthly.map(x=>Math.abs(x)))*100)}%`}}/></div><b className={v<0?'negative-text':''}>{i>month?'—':money(v)}</b></div>)}</div></Panel></div></div>}
 {tab==='Positions'&&<Page><Panel title="Open Positions" sub="Every active position from the engine" badge={`${positions.length} OPEN`}><PositionTable positions={positions} onClose={close}/></Panel></Page>}
 {tab==='Trades'&&<Page><Panel title="Trade History" sub="Complete engine execution ledger" badge={`${trades.length} EVENTS`}><TradeTable trades={trades}/></Panel></Page>}
 {tab==='Signals'&&<Page><Panel title="Scanner Signals" sub="Live candidates forwarded by the scanner" badge={scannerOk?'LISTENING':'OFFLINE'}><SignalTable candidates={candidates}/></Panel></Page>}
 {(tab==='Bot Controls'||tab==='Risk Settings')&&<Page><Panel title="Bot Controls & Risk" sub="Paper execution settings"><div className="control-buttons wide"><button className="pause-btn" onClick={()=>setPaused(!paused)}>{paused?'▶ Resume Bot':'Ⅱ Pause Bot'}</button><button className="stop-btn" onClick={()=>positions.forEach(close)}>● Close All</button></div><div className="settings-grid"><Field label="Max Position Size" value={size} set={setSize} suffix="USD"/><Field label="Stop Loss" value={sl} set={setSl} suffix="%"/><Field label="Take Profit" value={tp} set={setTp} suffix="%"/><Field label="Max Concurrent Positions" value="5" suffix="POSITIONS"/></div><div className="warning"><b>Automatic exit engine</b><p>Paper positions are managed by the trading engine. The dashboard only sends management commands; it does not execute wallet transactions.</p></div></Panel></Page>}
 {tab==='Calculator'&&<div className="split-page"><Panel title="Position Calculator" sub="Plan risk before entry"><Field label="Account Balance" value="100" suffix="USD"/><Field label="Risk Per Trade" value="2" suffix="%"/><Field label="Entry Price" value="0.000000" suffix="USD"/><Field label="Stop Price" value="0.000000" suffix="USD"/><div className="calc-result"><span>Maximum risk</span><b>$2.00</b></div><button className="primary-btn">Calculate Position</button></Panel><Panel title="Live Risk Profile" sub="Current dashboard settings"><Risk name="Position Size" value={`$${size}.00`}/><Risk name="Stop Loss" value={`${sl}%`}/><Risk name="Take Profit" value={`${tp}%`}/><Risk name="Engine" value={engineOk?'CONNECTED':'OFFLINE'} green={engineOk}/></Panel></div>}
 {tab==='Profit Goals'&&<div className="split-page"><Panel title="Profit Goal" sub="Track realized profit against your target"><div className="goal-big">{money(stats.pnl)} <small>/ ${Number(goal||0).toLocaleString()}</small></div><div className="goal-progress"><i style={{width:`${Math.min(100,Math.max(0,stats.pnl/Math.max(1,Number(goal))*100))}%`}}/></div><Field label="Target Profit" value={goal} set={setGoal} suffix="USD"/><button className="primary-btn">Update Goal</button></Panel><Panel title="Goal Stats" sub="Based on actual closed trades"><Risk name="Current Profit" value={money(stats.pnl)} green={stats.pnl>=0}/><Risk name="Remaining" value={fmtUsd(Math.max(0,Number(goal)-stats.pnl))}/><Risk name="Progress" value={`${Math.max(0,stats.pnl/Math.max(1,Number(goal))*100).toFixed(1)}%`}/></Panel></div>}
 {tab==='Settings'&&<div className="split-page"><Panel title="Connections" sub="Local services used by this dashboard"><Risk name="Trading Engine" value={engineOk?'CONNECTED':'OFFLINE'} green={engineOk}/><Risk name="Scanner" value={scannerOk?'CONNECTED':'OFFLINE'} green={scannerOk}/><Risk name="Engine URL" value={API.engine}/><Risk name="Scanner URL" value={API.scanner}/></Panel><Panel title="Safety" sub="Live trading protection"><div className="warning"><b>Paper mode is locked in</b><p>This dashboard does not collect or display private keys. Live wallet execution is intentionally kept outside the dashboard.</p></div></Panel></div>}
 </main></div>}

function Page({children}:{children:React.ReactNode}){return <div className="page-stack">{children}</div>}
function Risk({name,value,green=false}:{name:string;value:string;green?:boolean}){return <div className="risk-row"><span>{name}</span><b className={green?'green-text':''}>{value}</b></div>}
function EquityChart({trades,positions}:{trades:Trade[];positions:Position[]}){const sells=trades.filter(t=>t.type==='SELL').slice(-30);let eq=100;const pts=sells.map((t,i)=>{eq+=Number(t.pnlUsd||0);return {x:(i/Math.max(1,sells.length-1))*100,y:eq}});if(!pts.length)pts.push({x:0,y:100},{x:100,y:100});const min=Math.min(...pts.map(p=>p.y),90),max=Math.max(...pts.map(p=>p.y),110),range=Math.max(1,max-min);const d=pts.map((p,i)=>`${i?'L':'M'} ${p.x*8.1+20} ${245-((p.y-min)/range)*205}`).join(' ');return <div className="chart-wrap"><div className="chart-y"><span>${max.toFixed(0)}</span><span>${((max+min)/2).toFixed(0)}</span><span>${min.toFixed(0)}</span></div><svg viewBox="0 0 840 270" preserveAspectRatio="none"><g className="gridlines"><path d="M0 40H840M0 100H840M0 160H840M0 220H840"/></g><path className="area" d={`${d} L 840 270 L 20 270 Z`}/><path className="line" d={d}/></svg><div className="chart-x"><span>Start</span><span>Recent</span><span>{sells.length} closed</span></div></div>}
function PositionTable({positions,onClose}:{positions:Position[];onClose:(p:Position)=>void}){if(!positions.length)return <div className="empty-row"><div className="empty-icon">◇</div><b>No open positions</b><p>Qualifying scanner signals will appear here when the engine accepts them.</p></div>;return <div className="table"><div className="table-head"><span>ASSET</span><span>ENTRY</span><span>CURRENT</span><span>P/L</span><span>P/L %</span><span>SIZE</span><span>OPENED</span><span>ACTION</span></div>{positions.map(p=>{const pnl=(p.currentPriceUsd-p.entryPriceUsd)*p.quantity;const pct=p.entryPriceUsd?pnl/p.amountUsd*100:0;return <div className="table-row" key={p.id}><div><b>{p.symbol||'TOKEN'}</b><small>{p.tokenAddress.slice(0,8)}…</small></div><span>{fmtUsd(p.entryPriceUsd)}</span><span>{fmtUsd(p.currentPriceUsd)}</span><b className={pnl>=0?'green-text':'negative-text'}>{money(pnl)}</b><b className={pct>=0?'green-text':'negative-text'}>{fmtPct(pct)}</b><span>{fmtUsd(p.amountUsd)}</span><span>{new Date(p.openedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><button className="close-btn" onClick={()=>onClose(p)}>Close</button></div>})}</div>}
function TradeTable({trades}:{trades:Trade[]}){if(!trades.length)return <div className="large-empty"><div>⇄</div><h3>No trades yet</h3><p>Actual engine executions will appear here automatically.</p></div>;return <div className="table"><div className="table-head trade-head"><span>TYPE</span><span>ASSET</span><span>PRICE</span><span>AMOUNT</span><span>P/L</span><span>REASON</span><span>TIME</span></div>{trades.map(t=><div className="table-row trade-row" key={`${t.id}-${t.at}`}><b className={t.type==='BUY'?'cyan-text':'negative-text'}>{t.type}</b><b>{t.symbol||'TOKEN'}</b><span>{fmtUsd(t.priceUsd)}</span><span>{fmtUsd(t.amountUsd??t.proceedsUsd??0)}</span><b className={(t.pnlUsd||0)>=0?'green-text':'negative-text'}>{t.type==='SELL'?money(t.pnlUsd||0):'—'}</b><span>{t.reason||'scanner'}</span><span>{new Date(t.at).toLocaleString()}</span></div>)}</div>}
function SignalTable({candidates}:{candidates:Candidate[]}){if(!candidates.length)return <div className="large-empty"><div>◇</div><h3>No candidates right now</h3><p>The dashboard is listening to the scanner's /candidates endpoint.</p></div>;return <div className="table"><div className="table-head"><span>ASSET</span><span>SCORE</span><span>GRADE</span><span>LIQUIDITY</span><span>5M</span><span>VOLUME</span><span>RISK</span></div>{candidates.slice(0,50).map((c,i)=><div className="table-row" key={c.tokenAddress||c.address||i}><b>{c.symbol||'TOKEN'}</b><b>{Number(c.score||0).toFixed(0)}/100</b><b>{c.grade||'—'}</b><span>{fmtUsd(c.liquidityUsd||0)}</span><span className={Number(c.priceChange5mPct||0)>=0?'green-text':'negative-text'}>{fmtPct(c.priceChange5mPct||0)}</span><span>{fmtUsd(c.volume5mUsd||0)}</span><b className={c.riskPassed?'green-text':'negative-text'}>{c.riskPassed?'PASS':'BLOCK'}</b></div>)}</div>}
function ActivityList({trades,candidates}:{trades:Trade[];candidates:Candidate[]}){const items=[...trades.slice(-4).reverse().map(t=>({icon:t.type==='BUY'?'↗':'↘',title:`${t.type==='BUY'?'Bought':'Sold'} ${t.symbol||'token'}`,text:t.type==='SELL'?`P/L: ${money(t.pnlUsd||0)}`:`Amount: ${fmtUsd(t.amountUsd||0)}`,time:new Date(t.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),tone:t.type==='BUY'?'green':'orange'})),...candidates.slice(0,2).map(c=>({icon:'◇',title:'New Scanner Candidate',text:`${c.symbol||'TOKEN'} • Score ${Number(c.score||0).toFixed(0)}/100`,time:'NOW',tone:'purple'}))];if(!items.length)return <div className="empty-row"><div className="empty-icon">◌</div><b>Waiting for activity</b><p>Scanner and engine events will appear here.</p></div>;return <>{items.map((x,i)=><div className="activity-row" key={i}><div className={`activity-icon ${x.tone}`}>{x.icon}</div><div><b>{x.title}</b><span>{x.text}</span></div><small>{x.time}</small></div>)}</>}
function Calendar({daily,year,month}:{daily:Map<string,number>;year:number;month:number}){const count=new Date(year,month+1,0).getDate();return <div className="calendar">{Array.from({length:count},(_,i)=>{const d=i+1;const v=daily.get(`${year}-${month}-${d}`)||0;return <div key={d} className={`calendar-day ${v>0?'positive':v<0?'negative':''}`}><span>{d}</span><b>{v?money(v):'—'}</b></div>})}</div>}
